# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello rust!
  displayName: 'Run a one-line script'

- script: |
    rustup component add rustfmt-preview
    rustup component add clippy-preview --toolchain=nightly
  displayName: 'installing Cargo components'

- script: |
    cargo fmt --all -- --check
  displayName: 'Cargo fmt'

- script: |
    cargo clippy --all -- -D clippy_pedantic
  displayName: 'Cargo clippy'
