name: $(SourceBranchName)
jobs:
- template: azure-pipelines/build_unix.yml
  parameters:
    name: Linux
    vmImage: 'Ubuntu 16.04'
    artifactName: 'mdlint-linux.zip'
    repoName: 'robertohuertasm/mdlint'

- template: azure-pipelines/build_unix.yml
  parameters:
    name: MacOS
    vmImage: 'macOS-10.13'
    artifactName: 'mdlint-osx.zip'
    repoName: 'robertohuertasm/mdlint'

- template: azure-pipelines/build_windows.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    artifactName: 'mdlint-windows.zip'
    repoName: 'robertohuertasm/mdlint'
