cargo-features = ["edition"]

[package]
edition = '2018'
name = "rusty-markdownlint"
version = "0.1.0"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]

[dependencies]
console = "0.6.1"
comrak = "0.2.9"
typed-arena = "1.3.0"